name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: fenfenjoe/fenfenjoe.github.io
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm install --legacy-peer-deps && npm audit fix --force && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/
          CNAME: fenfenjoe.top